package logicwhilecollections;

public class FindTheNewlyAddedCharacter {

    /**
     * Problem:
     * Given two strings s and t, where t is generated by shuffling s and adding one extra character,
     * find and return the extra added character.
     *
     * Constraints:
     * - 0 <= s.length <= 1000
     * - t.length == s.length + 1
     * - s and t consist of lowercase English letters.
     *
     * Example:
     * Input: s = "abcd", t = "abcde"
     * Output: 'e'
     */
    public static char findTheDifference(String s, String t) {
        int xor = 0;
        for (char c : s.toCharArray()) {
            xor ^= c;
        }
        for (char c : t.toCharArray()) {
            xor ^= c;
        }
        return (char) xor;
    }

    public static void main(String[] args) {
        // Test case 1
        String s1 = "abcd";
        String t1 = "abcde";

        char result1 = findTheDifference(s1, t1);
        System.out.println("Test case 1 - Extra character: " + result1); // Expected: e

        // Test case 2
        String s2 = "";
        String t2 = "y";

        char result2 = findTheDifference(s2, t2);
        System.out.println("Test case 2 - Extra character: " + result2); // Expected: y

        // Additional test case with duplicates
        String s3 = "aabbcc";
        String t3 = "abcabcd";

        char result3 = findTheDifference(s3, t3);
        System.out.println("Test case 3 - Extra character: " + result3); // Expected: d
    }
}
